# .gitpod.yml

tasks:
  - name: Setup Environment
    init: |
      echo "✅ Installing Python dependencies..."
      pip install -r requirements.txt || true
      echo "✅ Environment ready."

ports:
  - port: 8000
    onOpen: open-preview
