# .gitpod.yml

tasks:
  - name: Setup Environment
    init: |
      echo "✅ Installing Python dependencies..."
      pip install -r requirements.txt || true
      echo "✅ Installing ngrok..."
      curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
      echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
      sudo apt update && sudo apt install -y ngrok
      echo "✅ Environment ready."

ports:
  - port: 8000
    onOpen: open-preview
