image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
  - command: |
      source venv/bin/activate
      python -u run_watchers.py
