from datetime import datetime
from app.core.models import JobConfig, Task
from app.core.interfaces import Job
from pathlib import Path
from app.services.executor_service import execute_task
from app.services.summary_service import summarise_text

class BaseDemoJob(Job):
    def job_id(self) -> str:
        return "base_demo"

    def job_name(self) -> str:
        return "Base Demo Job"

    def match(self, summary: str) -> list[Task]:
        return [
            Task(
                job_id=self.job_id(),
                source="watched/demo_inputs/test_demo_job.txt",
                description="Dummy task generated by base_demo",
                summary=summary,
                created_at=datetime.utcnow().isoformat(),
                action="print_report",
                payload={"message": summary}
            )
        ]

    def run(self, input: str | JobConfig):
        if isinstance(input, JobConfig):
            config = input
            print(f"[BaseDemoJob] 🚀 Running job on: {config}")
            input_path = Path(config.watch_dir)
            txt_files = sorted(input_path.glob("*.txt"))
            if not txt_files:
                print("[BaseDemoJob] ⚠️ No files to process.")
                return
            file_path = txt_files[0]
        else:
            file_path = Path(input)
            print(f"[BaseDemoJob] 🚀 Running job on: {file_path}")

        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()

        summary = summarise_text(text)
        tasks = self.match(summary)

        for task in tasks:
            execute_task(task)
